# Generated by Django 5.0.2 on 2025-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('employer', 'Работодатель'), ('admin', 'Администратор')], default='student', max_length=10),
        ),
    ]
