# Generated by Django 5.0.2 on 2025-03-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_alter_user_is_active_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='additional_requirements',
            field=models.TextField(blank=True, help_text='Дополнительные требования, не указанные в навыках', null=True),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='myproject.job'),
        ),
    ]
