# Generated by Django 5.0.2 on 2025-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_remove_job_requirements_job_additional_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='additional_requirements',
        ),
    ]
